Repository surbhi-droid-ui/hacktober2022, pull requests merged in 2022-10, with the labels that each got.

#2 Update main.java
  main.java
Labels: accepted

#3 Create coolapp.js
  coolapp.js
Labels: accepted

#4 2nd
  coolapp.js
Labels: accepted

#5 3rd
  main.java
Labels: hacktoberfest-accepted

#6 yo
  coolapp.js
Labels: accepted, hacktoberfest-accepted

#7 fhdgjfhk
  main.java
Labels: accepted, hacktoberfest-accepted

#8 json
  README.md
Labels: accepted, hacktoberfest-accepted
